[package]
name = "knyst-croptesting"
version = "0.1.0"
edition = "2021"

[dependencies]
knyst = { git = "https://github.com/ErikNatanael/knyst.git" }
#knyst = { path = "../knyst" }
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
indicatif = "0.17.8"
hound = "3.5.1"